#!/opt/homebrew/bin/python3
import sys
import random

def main():
    if len(sys.argv) < 3:
        print("usage\n\trand-range [min] [mix]\n")
        return
    print(random.randint(int(sys.argv[1]), int(sys.argv[2])))

if __name__ == "__main__": main()

