#!/opt/homebrew/bin/bash
name="$(ps -o command $$ | tail -n 1|sed 's/.*\///g'|tr -d ' \n\t')"; _=("$@"); argv=${_[*]}; argc=${#_[*]}; start="$(date +%s)"; dir=$(dirname "$(realpath $0)"); ws="$dir/ws/$name"; mkdir -p $ws; usage() { echo -e 'smil2 '; }; show_env() { echo -e "\nname: \t$name\n\nargv: \t$argv\n\nargc: \t$argc\n\nstart: \t$start\n\ndir: \t$dir\n\nws: \t$ws\n"; }

#show_env
#!/opt/homebrew/bin/bash
function smile { echo $1|rev; sleep 1; smile "$(rot_right ${1:0:$(( $(( ${#1}-1 )) / 2 ))}|rev)$(rot_left ${1:$(( $(( ${#1} )) / 2 ))})"; }; smile "${1:-"‚ñ≤" "‚ñ∂" "‚ñº" "‚óÄ" "‚ñ≥" "‚ñ∑" "‚ñΩ" "‚óÅ"}"
	
	

#echo -n '"'
#echo -n "▲ ▶ ▼ ◀ △ ▷ ▽ ◁"  | sed 's/ /" "/g'
#echo -n '"'
	 

